# Generated by Django 4.1.7 on 2023-05-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brans_Adı', models.CharField(max_length=30)),
                ('Ekleme_Tarihi', models.DateField()),
            ],
            options={
                'verbose_name': 'Branş',
                'verbose_name_plural': 'Branşlar',
            },
        ),
        migrations.CreateModel(
            name='Sporcu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kimlik_Numarası', models.CharField(max_length=30)),
                ('Ad', models.CharField(max_length=30)),
                ('Soyad', models.CharField(max_length=30)),
                ('Dogum', models.DateField()),
                ('Okulu', models.CharField(max_length=30)),
                ('VeliAdSoyad', models.CharField(max_length=30)),
                ('Telefon', models.CharField(max_length=30)),
                ('Adres', models.CharField(max_length=120)),
                ('Email', models.CharField(max_length=30)),
                ('Branslar', models.ManyToManyField(to='core.brans')),
            ],
            options={
                'verbose_name': 'Sporcu',
                'verbose_name_plural': 'Sporcular',
            },
        ),
        migrations.CreateModel(
            name='Antrenor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kimlik_Numarası', models.CharField(max_length=30)),
                ('Ad', models.CharField(max_length=30)),
                ('Soyad', models.CharField(max_length=30)),
                ('Telefon', models.CharField(max_length=30)),
                ('Branslar', models.ManyToManyField(to='core.sporcu')),
            ],
            options={
                'verbose_name': 'Antrenor',
                'verbose_name_plural': 'Antrenorler',
            },
        ),
    ]
